apiVersion: v1
kind: Pod
metadata:
  name: ppsapp-nodeport
  labels:
    app: pps
    type: nodeport
spec:
  containers:
  - name: ppsapp
    image: mypps:v0.2
    imagePullPolicy: Never
    ports:
    - containerPort: 1250
---
apiVersion: v1
kind: Service
metadata:
  name: ppsapp-nodeport
  labels:
    app: pps
    type: nodeport
spec:
  type: NodePort
  ports:
  - port: 1025
    protocol: UDP
  selector:
    app: pps
    type: nodeport
